name: Deploy to Kind Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker
      # - name: Login to Docker Registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # # 3. Build and push Docker image
      # - name: Build and Push Docker Image
      #   run: |
      #     IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/simple-app
      #     docker build -t $IMAGE_NAME:latest ./app
      #     docker push $IMAGE_NAME:latest
      #     echo "IMAGE=$IMAGE_NAME:latest" >> $GITHUB_ENV

      # 4. Setup kubectl and kubeconfig
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > kubeconfig
          mkdir -p $HOME/.kube
          mv kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl cluster-info

      # 5. Install Helm
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      # 6. Deploy to Kind using Helm
      - name: Helm Deploy
        run: |
          helm upgrade --install my-simple-app ./helm-chart
            

      # 7. Verify deployment
      - name: Verify
        run: |
          kubectl get pods -o wide
          kubectl get svc
